import { NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import { sendPowerAutomateWebhook, getAdminNotificationEmails } from '@/lib/webhook'

export async function POST() {
  try {
    const session = await getServerSession(authOptions)
    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const userName = session.user?.name || session.user?.email || 'Admin User'
    const recipientsList = getAdminNotificationEmails('VA', 'canApproveTimeOff')
    const recipientsStr = recipientsList.join(', ')

    const htmlBody = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta name="color-scheme" content="light dark">
    </head>
    <body style="font-family: 'Segoe UI', Arial, sans-serif; background-color: #f8fafc; padding: 24px; color: #0f172a;">
      <div style="max-width: 580px; margin: 0 auto; background: #ffffff; border-radius: 12px; border: 1px solid #cbd5e1; box-shadow: 0 4px 12px rgba(0,0,0,0.05); overflow: hidden;">
        <div style="background: #0f172a; padding: 24px 28px; border-bottom: 4px solid #3b82f6;">
          <div style="display: inline-block; background: #3b82f6; color: #ffffff; font-size: 11px; font-weight: 800; text-transform: uppercase; padding: 4px 10px; border-radius: 20px; letter-spacing: 0.05em; margin-bottom: 8px;">
            M365 Integration Test
          </div>
          <h1 style="font-size: 20px; font-weight: 800; color: #ffffff; margin: 0 0 4px 0;">🎉 Power Automate Webhook Verified</h1>
          <div style="font-size: 13px; color: #94a3b8;">Tabak Law Internal Management System</div>
        </div>

        <div style="padding: 28px;">
          <div style="background: #f1f5f9; border: 1px solid #e2e8f0; border-radius: 8px; padding: 20px; margin-bottom: 24px;">
            <div style="margin-bottom: 12px;">
              <div style="font-size: 11px; font-weight: 700; color: #64748b; text-transform: uppercase;">Triggered By</div>
              <div style="font-size: 15px; font-weight: 700; color: #0f172a;">${userName}</div>
            </div>
            <div style="margin-bottom: 12px;">
              <div style="font-size: 11px; font-weight: 700; color: #64748b; text-transform: uppercase;">Resolved Recipients (Role-Based)</div>
              <div style="font-size: 14px; font-weight: 600; color: #2563eb;">${recipientsStr || 'Admin Users'}</div>
            </div>
            <div>
              <div style="font-size: 11px; font-weight: 700; color: #64748b; text-transform: uppercase;">Timestamp</div>
              <div style="font-size: 14px; color: #334155;">${new Date().toLocaleString()}</div>
            </div>
          </div>

          <div style="text-align: center; margin-top: 24px;">
            <a href="https://tabak-dashboard.up.railway.app" target="_blank" style="display: inline-block; background: #2563eb; color: #ffffff !important; font-weight: 800; font-size: 15px; text-decoration: none; padding: 14px 28px; border-radius: 8px;">
              🚀 Open Dashboard &rarr;
            </a>
          </div>
        </div>
      </div>
    </body>
    </html>
    `

    const res = await sendPowerAutomateWebhook({
      event_type: 'test',
      title: '🧪 Test Notification: M365 Power Automate Webhook Verified',
      recipients: recipientsStr,
      agent_name: userName,
      lob: 'Tabak Dashboard',
      details: `Test payload generated by ${userName} at ${new Date().toLocaleString()}`,
      link: 'https://tabak-dashboard.up.railway.app',
      cta_label: '🚀 Open Dashboard',
      html_body: htmlBody,
    })

    if (!res.success) {
      return NextResponse.json({ success: false, error: res.error }, { status: 400 })
    }

    return NextResponse.json({ success: true, recipients: recipientsStr })
  } catch (err: any) {
    return NextResponse.json({ success: false, error: err.message }, { status: 500 })
  }
}
